// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: sys.proto

package server

import (
	"context"

	"ordering-platform/rpc/sys/internal/logic/deptservice"
	"ordering-platform/rpc/sys/internal/svc"
	"ordering-platform/rpc/sys/sysclient"
)

type DeptServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedDeptServiceServer
}

func NewDeptServiceServer(svcCtx *svc.ServiceContext) *DeptServiceServer {
	return &DeptServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeptServiceServer) DeptAdd(ctx context.Context, in *sysclient.DeptAddReq) (*sysclient.DeptAddResp, error) {
	l := deptservicelogic.NewDeptAddLogic(ctx, s.svcCtx)
	return l.DeptAdd(in)
}

func (s *DeptServiceServer) DeptUpdate(ctx context.Context, in *sysclient.DeptUpdateReq) (*sysclient.DeptUpdateResp, error) {
	l := deptservicelogic.NewDeptUpdateLogic(ctx, s.svcCtx)
	return l.DeptUpdate(in)
}

func (s *DeptServiceServer) DeptDelete(ctx context.Context, in *sysclient.DeptDeleteReq) (*sysclient.DeptDeleteResp, error) {
	l := deptservicelogic.NewDeptDeleteLogic(ctx, s.svcCtx)
	return l.DeptDelete(in)
}

func (s *DeptServiceServer) DeptInfo(ctx context.Context, in *sysclient.DeptInfoReq) (*sysclient.DeptInfoResp, error) {
	l := deptservicelogic.NewDeptInfoLogic(ctx, s.svcCtx)
	return l.DeptInfo(in)
}

func (s *DeptServiceServer) DeptList(ctx context.Context, in *sysclient.DeptListReq) (*sysclient.DeptListResp, error) {
	l := deptservicelogic.NewDeptListLogic(ctx, s.svcCtx)
	return l.DeptList(in)
}
