// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type AddMenuReq struct {
	MenuType        string  `json:"menuType"`            // 菜单类型
	Title           string  `json:"title"`               // 菜单标题
	Sort            int32   `json:"sort"`                // 显示排序
	ParentMenuId    int64   `json:"parentMenuId"`        // 上级菜单
	Icon            string  `json:"icon,optional"`       // 图标
	Name            string  `json:"name,optional"`       // 路由名称
	Component       string  `json:"component,optional"`  // 组件路径
	Path            string  `json:"path,optional"`       // 路由地址
	Permission      string  `json:"permission,optional"` // 权限标识
	HideInMenu      bool    `json:"hideInMenu,optional"`
	IgnoreKeepAlive bool    `json:"ignoreKeepAlive,optional"`
	LinkFlag        bool    `json:"linkFlag,optional"`
	Link            string  `json:"link,optional"` // 组件路径
	Disabled        bool    `json:"disabled,optional"`
	SelectApi       []int64 `json:"selectApi,optional"`
}

type AddMenuResp struct {
}

type ApiListData struct {
	Id         int64  `json:"id"`
	Handle     string `json:"handle"`     // 方法名
	Title      string `json:"title"`      // 方法描述
	Path       string `json:"path"`       // 请求路径
	Type       string `json:"type"`       // 类型 1 系统 2 业务
	Action     string `json:"action"`     // 请求方式
	CreateTime string `json:"createTime"` // 创建时间
}

type ApiListReq struct {
	Type     string `form:"type,optional"`       // 系统 业务
	Action   string `form:"action,optional"`     // 请求方法 GET POST DELETE PUT
	PageNum  int64  `form:"pageNum,default=1"`   //  第几页
	PageSize int64  `form:"pageSize,default=10"` // 每页的数量
}

type ApiListResp struct {
	Total int64          `json:"total"`
	Data  []*ApiListData `json:"data"`
}

type DeleteMenuReq struct {
	MenuId int64 `path:"menuId"`
}

type DeleteMenuResp struct {
}

type InitApiReq struct {
}

type InitApiResp struct {
}

type ListMenuData struct {
	MenuId          int64  `json:"menuId"`
	MenuType        string `json:"menuType"`     // 菜单类型
	Title           string `json:"title"`        // 菜单标题
	Sort            int32  `json:"sort"`         // 显示排序
	ParentMenuId    int64  `json:"parentMenuId"` // 上级菜单
	Icon            string `json:"icon"`         // 图标
	Name            string `json:"name"`         // 路由名称
	Component       string `json:"component"`    // 组件路径
	Path            string `json:"path"`         // 路由地址
	Permission      string `json:"permission"`   // 权限标识
	HideInMenu      bool   `json:"hideInMenu"`
	IgnoreKeepAlive bool   `json:"ignoreKeepAlive"`
	LinkFlag        bool   `json:"linkFlag"`
	Link            string `json:"link"` // 组件路径
	Disabled        bool   `json:"disabled"`
}

type ListMenuReq struct {
}

type ListMenuResp struct {
	Data []*ListMenuData `json:"data"`
}

type LoginReq struct {
	Username string `json:"username"` //用户名
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
}

type Menu struct {
	MenuId       int64     `json:"menuId"`
	ParentMenuId int64     `json:"parentMenuId"`
	Name         string    `json:"name"`      // 路由名称
	Path         string    `json:"path"`      // 路由地址
	Component    string    `json:"component"` // 组件地址
	MenuMate     *MenuMate `json:"meta"`
	Children     []*Menu   `json:"children,omitempty"`
}

type MenuInfoData struct {
	MenuId          int64   `json:"menuId"`
	MenuType        string  `json:"menuType"`     // 菜单类型
	Title           string  `json:"title"`        // 菜单标题
	Sort            int32   `json:"sort"`         // 显示排序
	ParentMenuId    int64   `json:"parentMenuId"` // 上级菜单
	Icon            string  `json:"icon"`         // 图标
	Name            string  `json:"name"`         // 路由名称
	Component       string  `json:"component"`    // 组件路径
	Path            string  `json:"path"`         // 路由地址
	Permission      string  `json:"permission"`   // 权限标识
	HideInMenu      bool    `json:"hideInMenu"`
	IgnoreKeepAlive bool    `json:"ignoreKeepAlive"`
	LinkFlag        bool    `json:"linkFlag"`
	Link            string  `json:"link"` // 组件路径
	Disabled        bool    `json:"disabled"`
	SelectApi       []int64 `json:"selectApi"`
}

type MenuInfoReq struct {
	MenuId int64 `path:"menuId"`
}

type MenuMate struct {
	Title                    string `json:"title"`                    // 菜单名称
	Order                    int64  `json:"order"`                    // 排序
	Icon                     string `json:"icon"`                     // 图标
	HideInMenu               bool   `json:"hideInMenu"`               // 是否隐藏
	KeepAlive                bool   `json:"keepAlive"`                // 是否缓存
	MenuVisibleWithForbidden bool   `json:"menuVisibleWithForbidden"` // 是否启用
	Link                     string `json:"link"`                     // 用于配置外链跳转路径，会在新窗口打开。
}

type UpdateMenuReq struct {
	MenuId          int64   `path:"menuId"`
	MenuType        string  `json:"menuType"`            // 菜单类型
	Title           string  `json:"title"`               // 菜单标题
	Sort            int32   `json:"sort"`                // 显示排序
	ParentMenuId    int64   `json:"parentMenuId"`        // 上级菜单
	Icon            string  `json:"icon,optional"`       // 图标
	Name            string  `json:"name,optional"`       // 路由名称
	Component       string  `json:"component,optional"`  // 组件路径
	Path            string  `json:"path,optional"`       // 路由地址
	Permission      string  `json:"permission,optional"` // 权限标识
	HideInMenu      bool    `json:"hideInMenu,optional"`
	IgnoreKeepAlive bool    `json:"ignoreKeepAlive,optional"`
	LinkFlag        bool    `json:"linkFlag,optional"`
	Link            string  `json:"link,optional"` // 组件路径
	Disabled        bool    `json:"disabled,optional"`
	SelectApi       []int64 `json:"selectApi,optional"`
}

type UpdateMenuResp struct {
}

type UserInfoResp struct {
	Avater   string   `json:"avater"`
	Roles    []string `json:"roles"`
	UserId   string   `json:"userId"`
	Username string   `json:"username"`
	Desc     string   `json:"desc"`
	HomePath string   `json:"homePath"`
}
