// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type InitApiReq struct {
}

type InitApiResp struct {
}

type LoginReq struct {
	Username string `json:"username"` //用户名
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
}

type Menu struct {
	MenuId       int64    `json:"menuId"`
	ParentMenuId int64    `json:"parentMenuId"`
	Name         string   `json:"name"`      // 路由名称
	Path         string   `json:"path"`      // 路由地址
	Component    string   `json:"component"` // 组件地址
	MenuMate     MenuMate `json:"meta"`
	Children     []Menu   `json:"children,omitempty"`
}

type MenuMate struct {
	Title                    string `json:"title"`                    // 菜单名称
	Order                    int64  `json:"order"`                    // 排序
	Icon                     string `json:"icon"`                     // 图标
	HideInMenu               bool   `json:"hideInMenu"`               // 是否隐藏
	KeepAlive                bool   `json:"keepAlive"`                // 是否缓存
	MenuVisibleWithForbidden bool   `json:"menuVisibleWithForbidden"` // 是否启用
	Link                     string `json:"link"`                     // 用于配置外链跳转路径，会在新窗口打开。
}

type UserInfoResp struct {
	Avater   string   `json:"avater"`
	Roles    []string `json:"roles"`
	UserId   string   `json:"userId"`
	Username string   `json:"username"`
	Desc     string   `json:"desc"`
	HomePath string   `json:"homePath"`
}
