// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: sys.proto

package server

import (
	"context"

	"ordering-platform/rpc/sys/internal/logic/apiservice"
	"ordering-platform/rpc/sys/internal/svc"
	"ordering-platform/rpc/sys/sysclient"
)

type ApiServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedApiServiceServer
}

func NewApiServiceServer(svcCtx *svc.ServiceContext) *ApiServiceServer {
	return &ApiServiceServer{
		svcCtx: svcCtx,
	}
}

// 初始化Api
func (s *ApiServiceServer) InitApi(ctx context.Context, in *sysclient.InitApiReq) (*sysclient.InitApiResp, error) {
	l := apiservicelogic.NewInitApiLogic(ctx, s.svcCtx)
	return l.InitApi(in)
}

func (s *ApiServiceServer) ListApi(ctx context.Context, in *sysclient.ApiListReq) (*sysclient.ApiListResp, error) {
	l := apiservicelogic.NewListApiLogic(ctx, s.svcCtx)
	return l.ListApi(in)
}
