// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: sys.proto

package server

import (
	"context"

	"ordering-platform/rpc/sys/internal/logic/tokenservice"
	"ordering-platform/rpc/sys/internal/svc"
	"ordering-platform/rpc/sys/sysclient"
)

type TokenServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedTokenServiceServer
}

func NewTokenServiceServer(svcCtx *svc.ServiceContext) *TokenServiceServer {
	return &TokenServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TokenServiceServer) CreateToken(ctx context.Context, in *sysclient.CreateTokenReq) (*sysclient.CreateTokenResp, error) {
	l := tokenservicelogic.NewCreateTokenLogic(ctx, s.svcCtx)
	return l.CreateToken(in)
}
