// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: sys.proto

package roleservice

import (
	"context"

	"ordering-platform/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq       = sysclient.AddMenuReq
	AddMenuResp      = sysclient.AddMenuResp
	ApiInfo          = sysclient.ApiInfo
	ApiListReq       = sysclient.ApiListReq
	ApiListResp      = sysclient.ApiListResp
	DeleteMenuReq    = sysclient.DeleteMenuReq
	DeleteMenuResp   = sysclient.DeleteMenuResp
	DeptAddReq       = sysclient.DeptAddReq
	DeptAddResp      = sysclient.DeptAddResp
	DeptDeleteReq    = sysclient.DeptDeleteReq
	DeptDeleteResp   = sysclient.DeptDeleteResp
	DeptInfoReq      = sysclient.DeptInfoReq
	DeptInfoResp     = sysclient.DeptInfoResp
	DeptListData     = sysclient.DeptListData
	DeptListReq      = sysclient.DeptListReq
	DeptListResp     = sysclient.DeptListResp
	DeptUpdateReq    = sysclient.DeptUpdateReq
	DeptUpdateResp   = sysclient.DeptUpdateResp
	InitApiReq       = sysclient.InitApiReq
	InitApiResp      = sysclient.InitApiResp
	InitApiRouteData = sysclient.InitApiRouteData
	ListMenuData     = sysclient.ListMenuData
	ListMenuReq      = sysclient.ListMenuReq
	ListMenuResp     = sysclient.ListMenuResp
	LoginReq         = sysclient.LoginReq
	LoginResp        = sysclient.LoginResp
	MenuInfoReq      = sysclient.MenuInfoReq
	MenuInfoResp     = sysclient.MenuInfoResp
	RoleAddReq       = sysclient.RoleAddReq
	RoleAddResp      = sysclient.RoleAddResp
	RoleDeleteReq    = sysclient.RoleDeleteReq
	RoleDeleteResp   = sysclient.RoleDeleteResp
	RoleInfoReq      = sysclient.RoleInfoReq
	RoleInfoResp     = sysclient.RoleInfoResp
	RoleListData     = sysclient.RoleListData
	RoleListReq      = sysclient.RoleListReq
	RoleListResp     = sysclient.RoleListResp
	RoleUpdateReq    = sysclient.RoleUpdateReq
	RoleUpdateResp   = sysclient.RoleUpdateResp
	UpdateMenuReq    = sysclient.UpdateMenuReq
	UpdateMenuResp   = sysclient.UpdateMenuResp
	UserAddReq       = sysclient.UserAddReq
	UserAddResp      = sysclient.UserAddResp
	UserDeleteReq    = sysclient.UserDeleteReq
	UserDeleteResp   = sysclient.UserDeleteResp
	UserDetailReq    = sysclient.UserDetailReq
	UserDetailResp   = sysclient.UserDetailResp
	UserInfoReq      = sysclient.UserInfoReq
	UserInfoResp     = sysclient.UserInfoResp
	UserListData     = sysclient.UserListData
	UserListReq      = sysclient.UserListReq
	UserListResp     = sysclient.UserListResp
	UserUpdateReq    = sysclient.UserUpdateReq
	UserUpdateResp   = sysclient.UserUpdateResp

	RoleService interface {
		RoleAdd(ctx context.Context, in *RoleAddReq, opts ...grpc.CallOption) (*RoleAddResp, error)
		RoleUpdate(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*RoleUpdateResp, error)
		RoleDelete(ctx context.Context, in *RoleDeleteReq, opts ...grpc.CallOption) (*RoleDeleteResp, error)
		RoleInfo(ctx context.Context, in *RoleInfoReq, opts ...grpc.CallOption) (*RoleInfoResp, error)
		RoleList(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListResp, error)
	}

	defaultRoleService struct {
		cli zrpc.Client
	}
)

func NewRoleService(cli zrpc.Client) RoleService {
	return &defaultRoleService{
		cli: cli,
	}
}

func (m *defaultRoleService) RoleAdd(ctx context.Context, in *RoleAddReq, opts ...grpc.CallOption) (*RoleAddResp, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.RoleAdd(ctx, in, opts...)
}

func (m *defaultRoleService) RoleUpdate(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*RoleUpdateResp, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.RoleUpdate(ctx, in, opts...)
}

func (m *defaultRoleService) RoleDelete(ctx context.Context, in *RoleDeleteReq, opts ...grpc.CallOption) (*RoleDeleteResp, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.RoleDelete(ctx, in, opts...)
}

func (m *defaultRoleService) RoleInfo(ctx context.Context, in *RoleInfoReq, opts ...grpc.CallOption) (*RoleInfoResp, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.RoleInfo(ctx, in, opts...)
}

func (m *defaultRoleService) RoleList(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListResp, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.RoleList(ctx, in, opts...)
}
