// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	sysapi "ordering-platform/api/admin/internal/handler/sys/api"
	sysdept "ordering-platform/api/admin/internal/handler/sys/dept"
	sysmenu "ordering-platform/api/admin/internal/handler/sys/menu"
	sysrole "ordering-platform/api/admin/internal/handler/sys/role"
	sysuser "ordering-platform/api/admin/internal/handler/sys/user"
	"ordering-platform/api/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// api 初始化
				Method:  http.MethodGet,
				Path:    "/initapi",
				Handler: sysapi.InitApiHandler(serverCtx),
			},
			{
				// api 列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: sysapi.ApiListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/sys/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckRole, serverCtx.PermissionAction},
			[]rest.Route{
				{
					// dept添加
					Method:  http.MethodPost,
					Path:    "/",
					Handler: sysdept.DeptAddHandler(serverCtx),
				},
				{
					// dept列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: sysdept.DeptListHandler(serverCtx),
				},
				{
					// dept更新
					Method:  http.MethodPut,
					Path:    "/:deptId",
					Handler: sysdept.DeptUpdateHandler(serverCtx),
				},
				{
					// dept删除
					Method:  http.MethodDelete,
					Path:    "/:deptId",
					Handler: sysdept.DeptDeleteHandler(serverCtx),
				},
				{
					// dept详情
					Method:  http.MethodGet,
					Path:    "/:deptId",
					Handler: sysdept.DeptInfoHandler(serverCtx),
				},
				{
					// dept tree 结构获取
					Method:  http.MethodGet,
					Path:    "/tree",
					Handler: sysdept.DeptTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/dept"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckRole, serverCtx.PermissionAction},
			[]rest.Route{
				{
					// menu 添加
					Method:  http.MethodPost,
					Path:    "/",
					Handler: sysmenu.AddMenuHandler(serverCtx),
				},
				{
					// menu 列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: sysmenu.ListMenuHandler(serverCtx),
				},
				{
					// menu 更新
					Method:  http.MethodPut,
					Path:    "/:menuId",
					Handler: sysmenu.UpdateMenuHandler(serverCtx),
				},
				{
					// menu 删除
					Method:  http.MethodDelete,
					Path:    "/:menuId",
					Handler: sysmenu.DeleteMenuHandler(serverCtx),
				},
				{
					// menu 详情
					Method:  http.MethodGet,
					Path:    "/:menuId",
					Handler: sysmenu.MenuInfoHandler(serverCtx),
				},
				{
					// menu tree 结构获取
					Method:  http.MethodGet,
					Path:    "/tree",
					Handler: sysmenu.TreeMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckRole, serverCtx.PermissionAction},
			[]rest.Route{
				{
					// role添加
					Method:  http.MethodPost,
					Path:    "/",
					Handler: sysrole.RoleAddHandler(serverCtx),
				},
				{
					// role列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: sysrole.RoleListHandler(serverCtx),
				},
				{
					// role更新
					Method:  http.MethodPut,
					Path:    "/:roleId",
					Handler: sysrole.RoleUpdateHandler(serverCtx),
				},
				{
					// role删除
					Method:  http.MethodDelete,
					Path:    "/:roleId",
					Handler: sysrole.RoleDeleteHandler(serverCtx),
				},
				{
					// role详情
					Method:  http.MethodGet,
					Path:    "/:roleId",
					Handler: sysrole.RoleInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckRole, serverCtx.PermissionAction},
			[]rest.Route{
				{
					// user添加
					Method:  http.MethodPost,
					Path:    "/",
					Handler: sysuser.UserAddHandler(serverCtx),
				},
				{
					// user列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: sysuser.UserListHandler(serverCtx),
				},
				{
					// user更新
					Method:  http.MethodPut,
					Path:    "/:userId",
					Handler: sysuser.UserUpdateHandler(serverCtx),
				},
				{
					// user删除
					Method:  http.MethodDelete,
					Path:    "/:userId",
					Handler: sysuser.UserDeleteHandler(serverCtx),
				},
				{
					// user详情
					Method:  http.MethodGet,
					Path:    "/:userId",
					Handler: sysuser.UserInfoHandler(serverCtx),
				},
				{
					// 获取用户权限码,按钮级别的权限
					Method:  http.MethodGet,
					Path:    "/codes",
					Handler: sysuser.UserCodesHandler(serverCtx),
				},
				{
					// 登录获取用户信息
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: sysuser.UserDetailHandler(serverCtx),
				},
				{
					// 获取用户菜单,主菜单和一级菜单
					Method:  http.MethodGet,
					Path:    "/menus",
					Handler: sysuser.UserMenusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/api/sys/user/login",
				Handler: sysuser.UserLoginHandler(serverCtx),
			},
		},
	)
}
