// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: sys.proto

package deptservice

import (
	"context"

	"ordering-platform/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq       = sysclient.AddMenuReq
	AddMenuResp      = sysclient.AddMenuResp
	ApiInfo          = sysclient.ApiInfo
	ApiListReq       = sysclient.ApiListReq
	ApiListResp      = sysclient.ApiListResp
	CreateTokenReq   = sysclient.CreateTokenReq
	CreateTokenResp  = sysclient.CreateTokenResp
	DeleteMenuReq    = sysclient.DeleteMenuReq
	DeleteMenuResp   = sysclient.DeleteMenuResp
	DeptAddReq       = sysclient.DeptAddReq
	DeptAddResp      = sysclient.DeptAddResp
	DeptDeleteReq    = sysclient.DeptDeleteReq
	DeptDeleteResp   = sysclient.DeptDeleteResp
	DeptInfoReq      = sysclient.DeptInfoReq
	DeptInfoResp     = sysclient.DeptInfoResp
	DeptListData     = sysclient.DeptListData
	DeptListReq      = sysclient.DeptListReq
	DeptListResp     = sysclient.DeptListResp
	DeptUpdateReq    = sysclient.DeptUpdateReq
	DeptUpdateResp   = sysclient.DeptUpdateResp
	InitApiReq       = sysclient.InitApiReq
	InitApiResp      = sysclient.InitApiResp
	InitApiRouteData = sysclient.InitApiRouteData
	ListMenuData     = sysclient.ListMenuData
	ListMenuReq      = sysclient.ListMenuReq
	ListMenuResp     = sysclient.ListMenuResp
	ListMenuRoleReq  = sysclient.ListMenuRoleReq
	MenuInfoReq      = sysclient.MenuInfoReq
	MenuInfoResp     = sysclient.MenuInfoResp
	RoleAddReq       = sysclient.RoleAddReq
	RoleAddResp      = sysclient.RoleAddResp
	RoleDeleteReq    = sysclient.RoleDeleteReq
	RoleDeleteResp   = sysclient.RoleDeleteResp
	RoleInfoReq      = sysclient.RoleInfoReq
	RoleInfoResp     = sysclient.RoleInfoResp
	RoleListData     = sysclient.RoleListData
	RoleListReq      = sysclient.RoleListReq
	RoleListResp     = sysclient.RoleListResp
	RoleUpdateReq    = sysclient.RoleUpdateReq
	RoleUpdateResp   = sysclient.RoleUpdateResp
	UpdateMenuReq    = sysclient.UpdateMenuReq
	UpdateMenuResp   = sysclient.UpdateMenuResp
	UserAddReq       = sysclient.UserAddReq
	UserAddResp      = sysclient.UserAddResp
	UserDeleteReq    = sysclient.UserDeleteReq
	UserDeleteResp   = sysclient.UserDeleteResp
	UserDetailReq    = sysclient.UserDetailReq
	UserDetailResp   = sysclient.UserDetailResp
	UserInfoReq      = sysclient.UserInfoReq
	UserInfoResp     = sysclient.UserInfoResp
	UserListData     = sysclient.UserListData
	UserListReq      = sysclient.UserListReq
	UserListResp     = sysclient.UserListResp
	UserUpdateReq    = sysclient.UserUpdateReq
	UserUpdateResp   = sysclient.UserUpdateResp
	UsernameReq      = sysclient.UsernameReq

	DeptService interface {
		DeptAdd(ctx context.Context, in *DeptAddReq, opts ...grpc.CallOption) (*DeptAddResp, error)
		DeptUpdate(ctx context.Context, in *DeptUpdateReq, opts ...grpc.CallOption) (*DeptUpdateResp, error)
		DeptDelete(ctx context.Context, in *DeptDeleteReq, opts ...grpc.CallOption) (*DeptDeleteResp, error)
		DeptInfo(ctx context.Context, in *DeptInfoReq, opts ...grpc.CallOption) (*DeptInfoResp, error)
		DeptList(ctx context.Context, in *DeptListReq, opts ...grpc.CallOption) (*DeptListResp, error)
	}

	defaultDeptService struct {
		cli zrpc.Client
	}
)

func NewDeptService(cli zrpc.Client) DeptService {
	return &defaultDeptService{
		cli: cli,
	}
}

func (m *defaultDeptService) DeptAdd(ctx context.Context, in *DeptAddReq, opts ...grpc.CallOption) (*DeptAddResp, error) {
	client := sysclient.NewDeptServiceClient(m.cli.Conn())
	return client.DeptAdd(ctx, in, opts...)
}

func (m *defaultDeptService) DeptUpdate(ctx context.Context, in *DeptUpdateReq, opts ...grpc.CallOption) (*DeptUpdateResp, error) {
	client := sysclient.NewDeptServiceClient(m.cli.Conn())
	return client.DeptUpdate(ctx, in, opts...)
}

func (m *defaultDeptService) DeptDelete(ctx context.Context, in *DeptDeleteReq, opts ...grpc.CallOption) (*DeptDeleteResp, error) {
	client := sysclient.NewDeptServiceClient(m.cli.Conn())
	return client.DeptDelete(ctx, in, opts...)
}

func (m *defaultDeptService) DeptInfo(ctx context.Context, in *DeptInfoReq, opts ...grpc.CallOption) (*DeptInfoResp, error) {
	client := sysclient.NewDeptServiceClient(m.cli.Conn())
	return client.DeptInfo(ctx, in, opts...)
}

func (m *defaultDeptService) DeptList(ctx context.Context, in *DeptListReq, opts ...grpc.CallOption) (*DeptListResp, error) {
	client := sysclient.NewDeptServiceClient(m.cli.Conn())
	return client.DeptList(ctx, in, opts...)
}
